SAS-1764 added prepare and test stage

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,16 +4,36 @@ variables:
   ADDON_NAME: "AgentEditor"
 
 stages:
+  - prepare
+  - test
   - build
   - package
 
-build_extension:
-  stage: build
+clone_extension:
+  stage: prepare
   image: nexus-docker-group.rnd.mendix.com/node:22
   script:
     - git clone --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.rnd.mendix.com/innovation-incubation/agent-editor.git temp_repo
+  artifacts:
+    paths:
+      - temp_repo/
+    expire_in: 1 hour
+
+test_extension:
+  stage: test
+  needs: [clone_extension]
+  image: nexus-docker-group.rnd.mendix.com/node:22
+  script:
     - cd temp_repo/agent-editor
     - npm ci
+    - npm run test
+
+build_extension:
+  stage: build
+  needs: [clone_extension, test_extension]
+  image: nexus-docker-group.rnd.mendix.com/node:22
+  script:
+    - cd temp_repo/agent-editor
     - npm run build
     - cd ../..
     - rm -rf extensions/agent-editor/*
@@ -29,11 +49,11 @@ mx_check:
   needs: [build_extension]
   image: nexus-docker-group.rnd.mendix.com/mxbuild:11.7.0
   script:
-    - mx check "GenAI Showcase App.mpr" || EXIT_CODE=$?
+    - mx check "GenAI Showcase App.mpr" && EXIT_CODE=0 || EXIT_CODE=$?
     - echo "Exit code $EXIT_CODE"
     - |
-      if [ "$EXIT_CODE" -ne 0 ]; then
-        echo "Build failed: Project contains errors"
+      if [ "$EXIT_CODE" -eq 1 ]; then
+        echo "Build failed - Project contains errors"
         exit 1
       fi
     - echo "Check completed (warnings/deprecations may exist but no errors)"
